<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends DocumentRepository
{
    public function searchTicket($id_user, $ref_fact) {
        $query = $this->createQueryBuilder();
        $ticket = $query->findOneBy(array('user_id' => $id_user, 'md5sum' => $ref_fact));

        return $ticket;
    }
}
